# actual working sample for dogfooding using latest issue2md action
name: issue2md
on:
  issues:
    types:
      - closed
jobs:
  issue2md:
    runs-on: ubuntu-latest
    name: Convert closed issue to markdown with published action
    if: ${{ !contains(github.event.issue.labels.*.name, 'test') &&
      github.event.issue.state_reason == 'completed' }}
    steps:
      - uses: actions/checkout@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Convert issue to markdown
        uses: go-zen-chu/issue2md@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-url: ${{ github.event.issue.html_url }}
          # By default, this action stores markdown to repository root. If you want to change export dir, make directory and change setting below.
          export-dir: ./issues
          auto-commit: true
          auto-push: true
